
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: echo-quarkus-knative-service
  labels:
    app: echo-quarkus-knative-service
    service: echo-quarkus-knative-service
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/sales-demo-app-dev/echo-quarkus-knative-service:v1
