apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: echo-quarkus-knative-service-monitor-queueadm
  name: order-ingestor-quarkus-knative-service-monitor-queueadm
  namespace: demo-app-monitor
spec:
  endpoints:
    - interval: 5s
      port: http-queueadm
      targetPort: 8022
  selector:
    matchLabels:
      serving.knative.dev/service: echo-quarkus-knative-service
