apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: echo-quarkus-knative-service-monitor-app
  name: order-ingestor-quarkus-knative-service-monitor-app
  namespace: demo-app-monitor
spec:
  endpoints:
    - interval: 5s
      port: http
      path: /metrics
  selector:
    matchLabels:
      serving.knative.dev/service: echo-quarkus-knative-service
