apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${project.artifactId}-${project.version}
  labels:
    app: ${project.artifactId}
    version: ${project.version}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${project.artifactId}
      version: ${project.version}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: ${project.artifactId}
        version: ${project.version}
    spec:
      containers:
        -
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 35
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
